import PyPDF2
import pandas as pd

# Open the PDF file
with open('/Users/achuilchoch/Downloads/2-data.pdf', 'rb') as file:
    pdf_reader = PyPDF2.PdfFileReader(file)
    num_pages = pdf_reader.numPages

    # Initialize an empty dataframe with the specified column names
    columns = ["Experiment ID", "Bacteria Type", "Bacteria Concentration (cells/mL)",
               "Encapsulation Method", "Nutrient Type", "Cement Type",
               "Water-Cement Ratio", "Sand/Cement Ratio", "Coarse Aggregate (kg)",
               "HRWR/Superplasticizer (kg)", "Fiber Content (kg)", "Curing Type",
               "Curing Duration (days)", "Initial Crack Width (mm)", "Final Crack Width (mm)",
               "Healing Time (days)", "Healing Conditions", "Healing Efficiency (%)",
               "Area Repair Rate (%)", "Anti-Seepage Repair Rate (%)", "Cracking Age (days)",
               "Water Permeability (L/m²/s)", "Microbial Survival Duration (days)"]
    df = pd.DataFrame(columns=columns)

    # Iterate through each page of the PDF
    for page_num in range(num_pages):
        page = pdf_reader.getPage(page_num)
        text = page.extractText()

        # Extract data based on specific patterns or keywords in the text
        experiment_id = ...
        bacteria_type = ...
        bacteria_concentration = ...
        encapsulation_method = ...
        nutrient_type = ...
        cement_type = ...
        water_cement_ratio = ...
        sand_cement_ratio = ...
        coarse_aggregate = ...
        hrwr_superplasticizer = ...
        fiber_content = ...
        curing_type = ...
        curing_duration = ...
        initial_crack_width = ...
        final_crack_width = ...
        healing_time = ...
        healing_conditions = ...
        healing_efficiency = ...
        area_repair_rate = ...
        anti_seepage_repair_rate = ...
        cracking_age = ...
        water_permeability = ...
        microbial_survival_duration = ...

        # Append the extracted data as a new row in the dataframe
        df.loc[len(df)] = [experiment_id, bacteria_type, bacteria_concentration,
                           encapsulation_method, nutrient_type, cement_type,
                           water_cement_ratio, sand_cement_ratio, coarse_aggregate,
                           hrwr_superplasticizer, fiber_content, curing_type,
                           curing_duration, initial_crack_width, final_crack_width,
                           healing_time, healing_conditions, healing_efficiency,
                           area_repair_rate, anti_seepage_repair_rate, cracking_age,
                           water_permeability, microbial_survival_duration]

# Save the dataframe to a spreadsheet file (e.g., CSV)
df.to_csv('research_data.csv', index=False)